version: '3.4'

services:
  api_gp_ventacorta:
    image: apigpventacorta:dev
    container_name: "API_GP_VentaCorta_1"
    build:
      args:
        BUILD_CONFIGURATION: Debug
        source: obj/Docker/empty/
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "API_GP_VentaCorta"
    volumes:
      - C:\Users\sofia\OneDrive\Escritorio\garantiaPacto\api-garantia-pacto-venta-corta\FUENTES_NET\API_GP_VentaCorta:C:\inetpub\wwwroot
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Remote Debugger:C:\remote_debugger:ro
    entrypoint: cmd /c "start /B C:\\ServiceMonitor.exe w3svc & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"

